stages:
  prepare:
    cmd: python src/prepare.py data/adult.csv
    deps:
    - data/adult.csv
    - src/prepare.py
    params:
    - prepare.split
  featurize:
    cmd: python src/featurize.py data
    deps:
    - data
    - src/featurize.py
    params:
    - featurize.featurelist
  train:
    cmd: python src/train.py
    deps:
    - data
    - src/train.py
    params:
    - train.n_estimators
  evaluate:
    cmd: python src/evaluate.py adult_model.pkl data scores.json prc.json roc.json
    deps:
    - adult_model.pkl
    - data
    - src/evaluate.py
    metrics:
    - scores.json:
        cache: false
    plots:
    - prc.json:
        cache: false
        x: recall
        y: precision
    - roc.json:
        cache: false
        x: fpr
        y: tpr
