prepare:
  split: 0.30

featurize:
  featurelist: ['age', 'workclass', 'fnlwgt', 'education', 'educational-num',
       'marital-status', 'occupation', 'relationship', 'race', 'gender',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'income']
  ngrams: 2

train:
  n_estimators: 10
